/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.stasiak.kotlin-application-conventions")
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("me.stasiak.app.AppKt")
}
